sonar.projectKey=Matta-Trade_Universal.Profile.Frontend
sonar.sources=.
sonar.tests=__tests__
sonar.test.inclusions=*.test.vue,*.test.ts,*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=.output/**,.nuxt/**,coverage/**,dist/**,node_modules/**,**/__tests__/**,**/__mocks__/**,**/plugins/**,**/store/**,**/stores/**,*.setup.js,*.config.*,*.scss,*.css,*.yml,*.yaml,*.md,*.json,*.html,utils/constants.js,utils/data.js
sonar.coverage.exclusions=.nuxt/**,coverage/**,dist/**,node_modules/**,**/__tests__/**,**/__mocks__/**,**/plugins/**,**/store/**,**/stores/**,*.setup.js,*.config.*,*.scss,*.css,*.yml,*.yaml,*.md,*.json,*.html,utils/constants.js,utils/data.js