import { it, expect, describe } from "vitest";
import currencyFormat from "~/utils/currencyFormat";

// Generated by CodiumAI

describe('currencyFormat', () => {

  // formats value as currency with default settings
  it('should format value as currency with default settings', () => {
    const value = 1234.56;
    const result = currencyFormat(value);
    expect(result).toBe("₦1,234.56");
  });

  // handles null or undefined value input
  it('should handle null or undefined value input', () => {
    const resultNull = currencyFormat(null);
    const resultUndefined = currencyFormat(undefined);
    expect(resultNull).toBe("₦0");
    expect(resultUndefined).toBe("₦0");
  });
});
