const countries = [
  // --- Africa ---
  { code: "DZ", label: "Algeria", phone: "213", min: 9, max: 9 },
  { code: "AO", label: "Angola", phone: "244", min: 9, max: 9 },
  { code: "BJ", label: "Benin", phone: "229", min: 8, max: 8 },
  { code: "BW", label: "Botswana", phone: "267", min: 7, max: 7 },
  { code: "BF", label: "Burkina Faso", phone: "226", min: 8, max: 8 },
  { code: "BI", label: "Burundi", phone: "257", min: 8, max: 8 },
  { code: "CM", label: "Cameroon", phone: "237", min: 9, max: 9 },
  { code: "CV", label: "Cape Verde", phone: "238", min: 7, max: 7 },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
    min: 8,
    max: 8,
  },
  { code: "TD", label: "Chad", phone: "235", min: 8, max: 8 },
  { code: "KM", label: "Comoros", phone: "269", min: 7, max: 7 },
  { code: "CG", label: "Congo", phone: "242", min: 9, max: 9 },
  {
    code: "CD",
    label: "Democratic Republic of Congo",
    phone: "243",
    min: 9,
    max: 9,
  },
  { code: "CI", label: "Cote d'Ivoire", phone: "225", min: 8, max: 8 },
  { code: "DJ", label: "Djibouti", phone: "253", min: 8, max: 8 },
  { code: "EG", label: "Egypt", phone: "20", min: 10, max: 10 },
  { code: "GQ", label: "Equatorial Guinea", phone: "240", min: 9, max: 9 },
  { code: "ER", label: "Eritrea", phone: "291", min: 7, max: 7 },
  { code: "ET", label: "Ethiopia", phone: "251", min: 9, max: 9 },
  { code: "GA", label: "Gabon", phone: "241", min: 7, max: 7 },
  { code: "GM", label: "Gambia", phone: "220", min: 7, max: 7 },
  { code: "GH", label: "Ghana", phone: "233", min: 9, max: 9 },
  { code: "GN", label: "Guinea", phone: "224", min: 9, max: 9 },
  { code: "GW", label: "Guinea-Bissau", phone: "245", min: 9, max: 9 },
  { code: "KE", label: "Kenya", phone: "254", min: 7, max: 9 },
  { code: "LS", label: "Lesotho", phone: "266", min: 8, max: 8 },
  { code: "LR", label: "Liberia", phone: "231", min: 8, max: 9 },
  { code: "LY", label: "Libya", phone: "218", min: 9, max: 10 },
  { code: "MG", label: "Madagascar", phone: "261", min: 9, max: 9 },
  { code: "MW", label: "Malawi", phone: "265", min: 9, max: 9 },
  { code: "ML", label: "Mali", phone: "223", min: 8, max: 8 },
  { code: "MR", label: "Mauritania", phone: "222", min: 8, max: 8 },
  { code: "MU", label: "Mauritius", phone: "230", min: 8, max: 8 },
  { code: "MA", label: "Morocco", phone: "212", min: 9, max: 9 },
  { code: "MZ", label: "Mozambique", phone: "258", min: 9, max: 9 },
  { code: "NA", label: "Namibia", phone: "264", min: 9, max: 9 },
  { code: "NE", label: "Niger", phone: "227", min: 8, max: 8 },
  { code: "NG", label: "Nigeria", phone: "234", min: 10, max: 10 },
  { code: "RW", label: "Rwanda", phone: "250", min: 9, max: 9 },
  { code: "ST", label: "Sao Tome and Principe", phone: "239", min: 7, max: 7 },
  { code: "SN", label: "Senegal", phone: "221", min: 9, max: 9 },
  { code: "SC", label: "Seychelles", phone: "248", min: 7, max: 7 },
  { code: "SL", label: "Sierra Leone", phone: "232", min: 8, max: 8 },
  { code: "SO", label: "Somalia", phone: "252", min: 8, max: 9 },
  { code: "ZA", label: "South Africa", phone: "27", min: 10, max: 10 },
  { code: "SS", label: "South Sudan", phone: "211", min: 9, max: 9 },
  { code: "SD", label: "Sudan", phone: "249", min: 9, max: 9 },
  { code: "TZ", label: "Tanzania", phone: "255", min: 9, max: 9 },
  { code: "TG", label: "Togo", phone: "228", min: 8, max: 8 },
  { code: "TN", label: "Tunisia", phone: "216", min: 8, max: 8 },
  { code: "UG", label: "Uganda", phone: "256", min: 9, max: 9 },
  { code: "ZM", label: "Zambia", phone: "260", min: 9, max: 9 },
  { code: "ZW", label: "Zimbabwe", phone: "263", min: 9, max: 9 },

  // --- Common Global Countries ---
  { code: "US", label: "United States", phone: "1", min: 10, max: 10 },
  { code: "CA", label: "Canada", phone: "1", min: 10, max: 10 },
  { code: "GB", label: "United Kingdom", phone: "44", min: 9, max: 10 },
  { code: "FR", label: "France", phone: "33", min: 9, max: 9 },
  { code: "DE", label: "Germany", phone: "49", min: 10, max: 11 },
  { code: "IT", label: "Italy", phone: "39", min: 9, max: 10 },
  { code: "ES", label: "Spain", phone: "34", min: 9, max: 9 },
  { code: "NL", label: "Netherlands", phone: "31", min: 9, max: 9 },
  { code: "RU", label: "Russia", phone: "7", min: 10, max: 10 },
  { code: "CN", label: "China", phone: "86", min: 11, max: 11 },
  { code: "IN", label: "India", phone: "91", min: 10, max: 10 },
  { code: "JP", label: "Japan", phone: "81", min: 10, max: 10 },
  { code: "KR", label: "South Korea", phone: "82", min: 8, max: 9 },
  { code: "BR", label: "Brazil", phone: "55", min: 10, max: 11 },
  { code: "MX", label: "Mexico", phone: "52", min: 10, max: 10 },
  { code: "AR", label: "Argentina", phone: "54", min: 10, max: 10 },
  { code: "CL", label: "Chile", phone: "56", min: 9, max: 9 },
  { code: "AU", label: "Australia", phone: "61", min: 9, max: 9 },
  { code: "NZ", label: "New Zealand", phone: "64", min: 8, max: 9 },
  { code: "SA", label: "Saudi Arabia", phone: "966", min: 9, max: 9 },
  { code: "AE", label: "United Arab Emirates", phone: "971", min: 9, max: 9 },
  { code: "TR", label: "Turkey", phone: "90", min: 10, max: 11 },
  { code: "IR", label: "Iran", phone: "98", min: 7, max: 10 },
  { code: "PK", label: "Pakistan", phone: "92", min: 10, max: 10 },
  { code: "BD", label: "Bangladesh", phone: "880", min: 10, max: 10 },
  { code: "ID", label: "Indonesia", phone: "62", min: 9, max: 11 },
  { code: "PH", label: "Philippines", phone: "63", min: 10, max: 10 },
  { code: "CO", label: "Colombia", phone: "57", min: 10, max: 10 },
  { code: "VE", label: "Venezuela", phone: "58", min: 10, max: 10 },
  { code: "PE", label: "Peru", phone: "51", min: 9, max: 9 },
  { code: "EC", label: "Ecuador", phone: "593", min: 9, max: 9 },
  { code: "UY", label: "Uruguay", phone: "598", min: 8, max: 8 },
  { code: "PY", label: "Paraguay", phone: "595", min: 9, max: 9 },
  { code: "BO", label: "Bolivia", phone: "591", min: 8, max: 8 },
  { code: "GT", label: "Guatemala", phone: "502", min: 8, max: 8 },
  { code: "HN", label: "Honduras", phone: "504", min: 8, max: 8 },
  { code: "SV", label: "El Salvador", phone: "503", min: 8, max: 8 },
  { code: "NI", label: "Nicaragua", phone: "505", min: 8, max: 8 },
  { code: "CR", label: "Costa Rica", phone: "506", min: 8, max: 8 },
  { code: "PA", label: "Panama", phone: "507", min: 8, max: 8 },
  { code: "JM", label: "Jamaica", phone: "1", min: 10, max: 10 },
  { code: "TT", label: "Trinidad and Tobago", phone: "1", min: 10, max: 10 },
  { code: "AD", label: "Andorra", phone: "376", min: 6, max: 6 },
  { code: "AF", label: "Afghanistan", phone: "93", min: 9, max: 9 },
  { code: "AG", label: "Antigua and Barbuda", phone: "1-268", min: 7, max: 7 },
  { code: "AI", label: "Anguilla", phone: "1-264", min: 7, max: 7 },
  { code: "AL", label: "Albania", phone: "355", min: 8, max: 8 },
  { code: "AM", label: "Armenia", phone: "374", min: 8, max: 8 },
  { code: "AS", label: "American Samoa", phone: "1-684", min: 7, max: 7 },
  { code: "AT", label: "Austria", phone: "43", min: 10, max: 10 },
  { code: "AW", label: "Aruba", phone: "297", min: 7, max: 7 },
  { code: "AX", label: "Åland Islands", phone: "358", min: 6, max: 6 },
  { code: "AZ", label: "Azerbaijan", phone: "994", min: 9, max: 9 },
  { code: "BA", label: "Bosnia and Herzegovina", phone: "387", min: 8, max: 8 },
  { code: "BB", label: "Barbados", phone: "1-246", min: 7, max: 7 },
  { code: "BE", label: "Belgium", phone: "32", min: 9, max: 9 },
  { code: "BG", label: "Bulgaria", phone: "359", min: 9, max: 9 },
  { code: "BH", label: "Bahrain", phone: "973", min: 8, max: 8 },
  { code: "BL", label: "Saint Barthélemy", phone: "590", min: 9, max: 9 },
  { code: "BM", label: "Bermuda", phone: "1-441", min: 7, max: 7 },
  { code: "BN", label: "Brunei Darussalam", phone: "673", min: 7, max: 7 },
  {
    code: "BQ",
    label: "Bonaire, Sint Eustatius and Saba",
    phone: "599",
    min: 7,
    max: 7,
  },
  { code: "BS", label: "Bahamas", phone: "1-242", min: 7, max: 7 },
  { code: "BT", label: "Bhutan", phone: "975", min: 8, max: 8 },
  { code: "BV", label: "Bouvet Island", phone: "47", min: 8, max: 8 },
  { code: "BY", label: "Belarus", phone: "375", min: 9, max: 9 },
  { code: "BZ", label: "Belize", phone: "501", min: 7, max: 7 },
  { code: "CC", label: "Cocos (Keeling) Islands", phone: "61", min: 7, max: 7 },
  { code: "CH", label: "Switzerland", phone: "41", min: 9, max: 9 },
  { code: "CK", label: "Cook Islands", phone: "682", min: 5, max: 5 },
  { code: "CU", label: "Cuba", phone: "53", min: 8, max: 8 },
  { code: "CW", label: "Curaçao", phone: "599", min: 7, max: 7 },
  { code: "CX", label: "Christmas Island", phone: "61", min: 7, max: 7 },
  { code: "CY", label: "Cyprus", phone: "357", min: 8, max: 8 },
  { code: "CZ", label: "Czechia", phone: "420", min: 9, max: 9 },
  { code: "DK", label: "Denmark", phone: "45", min: 8, max: 8 },
  { code: "DM", label: "Dominica", phone: "1-767", min: 7, max: 7 },
  { code: "DO", label: "Dominican Republic", phone: "1-809", min: 7, max: 7 },
  { code: "EE", label: "Estonia", phone: "372", min: 8, max: 8 },
  { code: "EH", label: "Western Sahara", phone: "212", min: 9, max: 9 },
  { code: "FI", label: "Finland", phone: "358", min: 9, max: 9 },
  { code: "FJ", label: "Fiji", phone: "679", min: 7, max: 7 },
  {
    code: "FM",
    label: "Micronesia (Federated States of)",
    phone: "691",
    min: 7,
    max: 7,
  },
  { code: "FO", label: "Faroe Islands", phone: "298", min: 6, max: 6 },
  { code: "GD", label: "Grenada", phone: "1-473", min: 7, max: 7 },
  { code: "GE", label: "Georgia", phone: "995", min: 9, max: 9 },
  { code: "GF", label: "French Guiana", phone: "594", min: 9, max: 9 },
  { code: "GG", label: "Guernsey", phone: "44", min: 9, max: 9 },
  { code: "GI", label: "Gibraltar", phone: "350", min: 8, max: 8 },
  { code: "GL", label: "Greenland", phone: "299", min: 6, max: 6 },
  { code: "GP", label: "Guadeloupe", phone: "590", min: 9, max: 9 },
  { code: "GR", label: "Greece", phone: "30", min: 10, max: 10 },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
    min: 6,
    max: 6,
  },
  { code: "GU", label: "Guam", phone: "1-671", min: 10, max: 10 },
  { code: "GY", label: "Guyana", phone: "592", min: 7, max: 7 },
  { code: "HK", label: "Hong Kong", phone: "852", min: 8, max: 8 },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
    min: 6,
    max: 6,
  },
  { code: "HR", label: "Croatia", phone: "385", min: 9, max: 9 },
  { code: "HT", label: "Haiti", phone: "509", min: 8, max: 8 },
  { code: "HU", label: "Hungary", phone: "36", min: 9, max: 9 },
  { code: "IE", label: "Ireland", phone: "353", min: 9, max: 9 },
  { code: "IM", label: "Isle of Man", phone: "44", min: 9, max: 9 },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
    min: 7,
    max: 7,
  },
  { code: "IQ", label: "Iraq", phone: "964", min: 10, max: 10 },
  { code: "IS", label: "Iceland", phone: "354", min: 7, max: 7 },
  { code: "JE", label: "Jersey", phone: "44", min: 9, max: 9 },
  { code: "JO", label: "Jordan", phone: "962", min: 9, max: 9 },
  { code: "KG", label: "Kyrgyzstan", phone: "996", min: 9, max: 9 },
  { code: "KH", label: "Cambodia", phone: "855", min: 9, max: 9 },
  { code: "KI", label: "Kiribati", phone: "686", min: 7, max: 7 },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
    min: 10,
    max: 10,
  },
  { code: "KP", label: "North Korea", phone: "850", min: 9, max: 9 },
  { code: "KW", label: "Kuwait", phone: "965", min: 8, max: 8 },
  { code: "KY", label: "Cayman Islands", phone: "1-345", min: 10, max: 10 },
  { code: "KZ", label: "Kazakhstan", phone: "7", min: 10, max: 10 },
  { code: "MC", label: "Monaco", phone: "377", min: 8, max: 9 },
  { code: "LI", label: "Liechtenstein", phone: "423", min: 7, max: 7 },
  { code: "VA", label: "Vatican City", phone: "379", min: 9, max: 9 },
  { code: "SM", label: "San Marino", phone: "378", min: 10, max: 10 },
  { code: "ME", label: "Montenegro", phone: "382", min: 8, max: 8 },
  { code: "RS", label: "Serbia", phone: "381", min: 9, max: 9 },
  { code: "MK", label: "North Macedonia", phone: "389", min: 8, max: 8 },
  { code: "SJ", label: "Svalbard and Jan Mayen", phone: "47", min: 8, max: 8 },
  { code: "MF", label: "Saint Martin", phone: "590", min: 9, max: 9 },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
    min: 6,
    max: 6,
  },
  { code: "WF", label: "Wallis and Futuna", phone: "681", min: 6, max: 6 },
  { code: "TV", label: "Tuvalu", phone: "688", min: 5, max: 5 },
  { code: "NR", label: "Nauru", phone: "674", min: 7, max: 7 },
  { code: "TO", label: "Tonga", phone: "676", min: 5, max: 5 },
  { code: "WS", label: "Samoa", phone: "685", min: 7, max: 7 },
  { code: "VU", label: "Vanuatu", phone: "678", min: 7, max: 7 },
  { code: "SB", label: "Solomon Islands", phone: "677", min: 7, max: 7 },
  { code: "FM", label: "Micronesia", phone: "691", min: 7, max: 7 },
  { code: "MH", label: "Marshall Islands", phone: "692", min: 7, max: 7 },
  { code: "PW", label: "Palau", phone: "680", min: 7, max: 7 },
  
];

export default countries;
