export const timezoneToCountry = {
    // 🌍 Africa
    "Africa/Lagos": "Nigeria",
    "Africa/Johannesburg": "South Africa",
    "Africa/Accra": "Ghana",
    "Africa/Abidjan": "Ivory Coast",
    "Africa/Cairo": "Egypt",
    "Africa/Nairobi": "Kenya",
    "Africa/Algiers": "Algeria",
    "Africa/Casablanca": "Morocco",
    "Africa/Dakar": "Senegal",
    "Africa/Harare": "Zimbabwe",
    "Africa/Kampala": "Uganda",
    "Africa/Lusaka": "Zambia",
    "Africa/Maputo": "Mozambique",
    "Africa/Windhoek": "Namibia",
    "Africa/Tripoli": "Libya",
    "Africa/Tunis": "Tunisia",
    "Africa/Bamako": "Mali",
    "Africa/Conakry": "Guinea",
    "Africa/Douala": "Cameroon",
    "Africa/Libreville": "Gabon",
    "Africa/Porto-Novo": "Benin",
    "Africa/Lome": "Togo",
    "Africa/Monrovia": "Liberia",
    "Africa/Banjul": "Gambia",
    "Africa/Niamey": "Niger",
    "Africa/Ouagadougou": "Burkina Faso",
    "Africa/Freetown": "Sierra Leone",
    "Africa/Mogadishu": "Somalia",
    "Africa/Addis_Ababa": "Ethiopia",
    "Africa/Asmara": "Eritrea",
    "Africa/Bujumbura": "Burundi",
    "Africa/Kigali": "Rwanda",

    // 🌍 Europe
    "Europe/London": "United Kingdom",
    "Europe/Paris": "France",
    "Europe/Berlin": "Germany",
    "Europe/Madrid": "Spain",
    "Europe/Rome": "Italy",
    "Europe/Amsterdam": "Netherlands",
    "Europe/Brussels": "Belgium",
    "Europe/Stockholm": "Sweden",
    "Europe/Oslo": "Norway",
    "Europe/Copenhagen": "Denmark",
    "Europe/Zurich": "Switzerland",
    "Europe/Vienna": "Austria",
    "Europe/Warsaw": "Poland",
    "Europe/Bucharest": "Romania",
    "Europe/Prague": "Czech Republic",
    "Europe/Athens": "Greece",
    "Europe/Dublin": "Ireland",
    "Europe/Budapest": "Hungary",
    "Europe/Helsinki": "Finland",
    "Europe/Lisbon": "Portugal",

    // 🌎 Americas
    "America/New_York": "United States",
    "America/Los_Angeles": "United States",
    "America/Chicago": "United States",
    "America/Toronto": "Canada",
    "America/Vancouver": "Canada",
    "America/Mexico_City": "Mexico",
    "America/Sao_Paulo": "Brazil",
    "America/Bogota": "Colombia",
    "America/Caracas": "Venezuela",
    "America/Argentina/Buenos_Aires": "Argentina",
    "America/Lima": "Peru",
    "America/Santiago": "Chile",
    "America/Montevideo": "Uruguay",
    "America/Panama": "Panama",

    // 🌏 Asia
    "Asia/Tokyo": "Japan",
    "Asia/Seoul": "South Korea",
    "Asia/Shanghai": "China",
    "Asia/Hong_Kong": "Hong Kong",
    "Asia/Singapore": "Singapore",
    "Asia/Bangkok": "Thailand",
    "Asia/Jakarta": "Indonesia",
    "Asia/Kuala_Lumpur": "Malaysia",
    "Asia/Dubai": "United Arab Emirates",
    "Asia/Kolkata": "India",
    "Asia/Manila": "Philippines",
    "Asia/Taipei": "Taiwan",
    "Asia/Ho_Chi_Minh": "Vietnam",
    "Asia/Riyadh": "Saudi Arabia",
    "Asia/Kuwait": "Kuwait",
    "Asia/Baghdad": "Iraq",
    "Asia/Tehran": "Iran",
    "Asia/Kathmandu": "Nepal"
  };